---
title: "cefitds"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

CEFI THREDDS catalog navigation using R

# Requirements

### CRAN 
  + [R v4.1+](https://www.r-project.org/)
  
  + [thredds](https://CRAN.R-project.org/package=thredds)
	
### Github
  + [cefi](https://github.com/BigelowLab/cefi)
  
# Suggested
  + [httr](https://CRAN.R-project.org/package=httr)

# Installation

```
remotes::install_github("BigelowLab/cefitds")
```

# Usage

Retrieve DatasetNode objects for a specific region, product suite and set of variables.  Each object contains the URL for the NetCDF connection.

```{r usage}
suppressPackageStartupMessages({
  library(cefitds)
  library(tidync)
  library(dplyr)
})

datasets = query_cefi(region = "northwest_atlantic",
                        product = "hindcast",
                        period = "monthly",
                        vars = c("btm_o2", "btm_temp"))
datasets
```


Pull the URLs out.

```{r urls}
r = node_extract_table(datasets) |>
  dplyr::glimpse()
```

Now use the [tidync](https://CRAN.R-project.org/package=tidync) package to open the connection.

```{r nc_open, warning=FALSE, message = FALSE}
tidync::tidync(r$url[1])
```